[features]
seeds = true
skip-lint = false
[programs.localnet]
whitehat = "WHATtP4qZ6GCva5NafqLaTKozQqr9VjL6SXWwCFvvyp"
[programs.devnet]
whitehat = "WHATtP4qZ6GCva5NafqLaTKozQqr9VjL6SXWwCFvvyp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
