[features]
seeds = true
skip-lint = false
[programs.localnet]
whitehat = "HATo3yGickypg7QCZJjZAAMYNicGatoDp6b1WKuYx7vm"
[programs.devnet]
whitehat = "HATo3yGickypg7QCZJjZAAMYNicGatoDp6b1WKuYx7vm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
