name: "Setup Anchor"
description: "Install Anchor, Solana CLI tools, and Node.js."
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: "Version of node.js to use"
    required: false
    default: "18.18.0" # LTS
  solana-cli-version:
    description: "Version of Solana CLI to use"
    required: false
    default: "1.16.15" # stable
  anchor-version:
    description: "Version of Anchor to use"
    required: false
    default: "0.28.0" # latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Solana CLI tools
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-cli-${{ runner.os }}-build-${{ inputs.solana-cli-version }}
    - name: Install Solana CLI tools
      run: sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.solana-cli-version }}/install)"
      shell: bash
    - name: Update PATH
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Anchor
      run: npm i -g @coral-xyz/anchor@${{ inputs.anchor-version }}
      shell: bash
